version: "2"
services:
  test:
    image: mytardis/mytardis-test
    build:
      context: ..
      dockerfile: docker-ci/Dockerfile
    environment:
      ELASTICSEARCH_URL: "http://es:9200"
    volumes:
      - ../tardis:/app/tardis
    depends_on:
      - pg
      - mysql
      - es
    links:
      - pg
      - mysql
      - es
  pg:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: --default-authentication-plugin=mysql_native_password
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
